config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  root "welcome#index"
  get "dashboard" => "dashboard#index", as: :dashboard

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :admins, shallow: true do
    resources :users
  end

  # Extra admin paths
  get "/all_users" => "admins#all_users"
  get "/all_pending_users" => "admins#all_pending_users"
  get "/all_admins" => "admins#all_admins"
  get "/all_transactions" => "admins#all_transactions"
  get "/view_transaction/:id" => "admins#view_transaction", as: "view_transaction"
  post "/users/:id/confirm_user" => "users#confirm_user", as: "confirm_user"
  post "/users/:id/approve_application" => "users#approve_application", as: "approve_application"
  post "/users/:id/deny_application" => "users#deny_application", as: "deny_application"
  post "/users/:id/verify_user" => "dashboard#verify_user", as: "verify_user"

  resources :wallets, only: [ :show ], shallow: true do
    resources :transactions, only: [ :index, :show, :new, :create ]
    resources :investments, only: [ :index, :show ]
  end

  resources :stocks, only: [ :show, :index ]

  get "/user_profile" => "dashboard#user_profile", as: "user_profile"
end

app/views/admins/_admin_top_bar.html.erb
<div class="<%= admin_flex_row_container_top %> sticky top-0 right-0 left-0">
  <div class="<%= admin_flex_row_container %>">
    <%= button_to image_tag('icons/JuanStocksIcon.png', height:40, width:40), admins_path, method: :get, :class => "cursor-pointer" %>
    <h2 class="<%=admin_logo_text%>">JuanStocks</h2>
  </div>
  <%= button_to image_tag('icons/Sign Out.png', height:21, width:21 ) + "Sign Out", destroy_user_session_path, method: :delete, :class => admin_sign_out_button  %>
</div>

app/views/admins/all_admins.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> px-[1rem] mt-[1rem]">
  <h1 class="<%=admin_main_header%>">All Juanstocks Admins</h1>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">First_name</th>
        <th class="<%=admin_thead_border%>">Last_name</th>
        <th class="<%=admin_thead_border%>">Email</th>
        <th class="<%=admin_thead_border%>">user_role</th>
      </tr>
    </thead>
    <tbody>
      <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.id %> </td>
        <td><%= admin.first_name %> </td>
        <td><%= admin.last_name %> </td>
        <td><%= admin.email %> </td>
        <td><%= admin.user_role %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/all_pending_users.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> px-[1rem] mt-[1rem]">
  <h1 class="<%=admin_main_header%>">Pending Users</h1>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">First Name</th>
        <th class="<%=admin_thead_border%>">Last Name</th>
        <th class="<%=admin_thead_border%>">Email</th>
        <th class="<%=admin_thead_border%>">Role</th>
        <th class="<%=admin_thead_border%>">Status</th>
        <th class="<%=admin_thead_border%>">Confirmed Timestamp</th>
        <th class="<%=admin_thead_border%>">Broker application</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr class="hover:bg-[#8B7DC324]">
        <td><%= user.id %> </td>
        <td><%= user.first_name %> </td>
        <td><%= user.last_name %> </td>
        <td><%= user.email %> </td>
        <td><%= user.user_role %> </td>
        <td><%= user.user_status %> </td>
        <% if user.confirmed_at == nil   %>
          <td> Account not confirmed </td>
        <% else %>
          <td><%= user.confirmed_at %> </td>
        <% end %>
        <% if user.user_status == "pending" %>
          <td><%= button_to "Approve application", approve_application_path(user.id), method: :post, :class=> "cursor-pointer bg-[#8B7DC3] hover:bg-[#FFA62B] px-[0.5rem] py-[0.5rem] rounded-lg text-white" %></td>
          <td><%= button_to "Deny application", deny_application_path(user.id), method: :post, :class=> "cursor-pointer bg-[hsl(0,74%,57%)] hover:bg-[#FFA62B] px-[0.5rem] py-[0.5rem] rounded-lg text-white" %></td>
        <% elsif user.user_status == "buyer_broker" %>
          <td>User is a broker</td>
        <% else %>
          <td>User has not applied</td>
        <% end %>
        <td><%= button_to image_tag('icons/Search.png', height:21, width:21 ), user_path(user), method: :get, :class=> admin_mini_button%></td>
      </tr> 
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/all_transactions.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> px-[1rem] mt-[1rem]">
  <h1 class="<%=admin_main_header%>">All Transactions</h1>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">User Email</th>
        <th class="<%=admin_thead_border%>">Transaction Type</th>
        <th class="<%=admin_thead_border%>">Shares</th>
        <th class="<%=admin_thead_border%>">Amount</th>
        <th class="<%=admin_thead_border%>">Stock Symbol</th>
        <th class="<%=admin_thead_border%>">Transaction Timestamp</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |tx| %>
      <% break if tx.wallet.user == nil%>
        <tr class="hover:bg-[#8B7DC324]">
          <td><%= tx.id %> </td>
          <td><%= tx.wallet.user.email %> </td>
          <td><%= tx.transaction_type %> </td>
          <td><%= tx.share_amount %> </td>
          <td><%= tx.price.format %> </td>
          <td><%= tx.stock_symbol %> </td>
          <td><%= tx.created_at.localtime.to_formatted_s(:long) %> </td>
          <td><%= button_to image_tag('icons/Search.png', height:21, width:21 ), view_transaction_path(tx.id), method: :get, :class=> admin_mini_button%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/all_users.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> px-[1rem] mt-[1rem]">
  <div class="<%=admin_flex_row_container%> justify-between">
    <h1 class="<%=admin_main_header%>">All Juanstocks Users</h1>
    <%= button_to image_tag('icons/NewUser.png', height:21, width:21 ) + "New User", new_admin_user_path(current_user), method: :get, :class => admin_dashboard_button %>
  </div>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">First Name</th>
        <th class="<%=admin_thead_border%>">Last Name</th>
        <th class="<%=admin_thead_border%>">Email</th>
        <th class="<%=admin_thead_border%>">Role</th>
        <th class="<%=admin_thead_border%>">Status</th>
        <th class="<%=admin_thead_border%>">Confirmed Timestamp</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr class="hover:bg-[#8B7DC324]">
        <td><%= user.id %> </td>
        <td><%= user.first_name %> </td>
        <td><%= user.last_name %> </td>
        <td><%= user.email %> </td>
        <td><%= user.user_role %> </td>
        <td><%= user.user_status %> </td>
        <% if user.confirmed_at == nil   %>
        <td> Account not confirmed </td>
        <% else %>
        <td><%= user.confirmed_at %> </td>
        <% end %>
        <td><%= button_to image_tag('icons/Search.png', height:21, width:21 ), user_path(user.id), method: :get, :class=> admin_mini_button%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admins/index.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> mt-[1rem]">
  <h1 class="<%=admin_main_header%> px-[1rem]"> Admin <%= current_user.first_name%> <%= current_user.last_name%> </h1>

  <div class="<%=admin_flex_row_container%>">
    <div class="<%=admin_flex_col_container%> px-[1rem]">
      <%= link_to image_tag('icons/AllUsers.png', height:21, width:21 ) + "All Users", all_users_path, :class => admin_dashboard_button %>
      <%= link_to image_tag('icons/PendingApprovals.png', height:21, width:21 ) + "Pending Approvals", all_pending_users_path, :class => admin_dashboard_button %>
      <%= link_to image_tag('icons/AllTransactions.png', height:21, width:21 ) + "Transactions", all_transactions_path, :class => admin_dashboard_button %>
      <%= link_to image_tag('icons/AllAdmins.png', height:21, width:21 ) + "All Admins", all_admins_path, :class => admin_dashboard_button %>
    </div>
    <div class="<%=admin_flex_col_container%> px-[1rem]">
      <p class="<%=admin_mini_header%>">Statistics</p>
      <div class="<%=admin_divider%>"></div>
      <p>Total Users : <%=@users.count%></p>
      <p>Total Buyers : <%=@buyers.count%></p>
      <p>Total Brokers : <%=@brokers.count%></p>
      <p>Total Transactions : <%=@transactions.count%></p>
    </div>
  </div>
</div>

app/views/admins/view_transaction.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> px-[1rem] mt-[1rem]">
<h1 class="<%=admin_main_header%>">Transaction #<%= @transaction.id %></div>
  <div class="<%=admin_flex_col_container%> px-[1rem]">
    <p class="<%=admin_mini_header%> pt-[1rem]">User Details</p>
    <div class="<%=admin_divider%>"></div>
    <p>First Name : <%= @user.first_name %></p>
    <p>Last Name : <%= @user.last_name %></p>
    <p>Role : <%= @user.user_role %> </p>
    <p>Status : <%= @user.user_status %> </p>
    <p>Wallet Balance : <%= @user.wallet.balance.format %> </p>
    <% if @user.confirmed_at == nil   %>
    <p> Account not confirmed </p>
    <% else %>
    <p>Account Confirmed : <%= @user.confirmed_at %></p>
    <% end %>
    <%= button_to image_tag('icons/Search.png', height:21, width:21 ) +'Show User', user_path(@user), method: :get, :class=> admin_dashboard_button %>
    <p class="<%=admin_mini_header%>">Transaction Details</p>
    <div class="<%=admin_divider%>"></div>
    <p>Transaction Type : <%= @transaction.transaction_type %></p>
    <% if @transaction.stock_symbol != nil %>
      <p>Stock Symbol : <%= @transaction.stock_symbol %></p>
      <p>Shares : <%= @transaction.share_amount %></p>
    <% end %>
    <p>Amount : <%= @transaction.price.format %></p>
    <p>Timestamp : <%= @transaction.created_at.localtime.to_formatted_s(:long) %></p>
  </div>
</div>