config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  root "welcome#index"
  get "dashboard" => "dashboard#index", as: :dashboard

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :admins, shallow: true do
    resources :users
  end

  # Extra admin paths
  get "/all_users" => "admins#all_users"
  get "/all_pending_users" => "admins#all_pending_users"
  get "/all_admins" => "admins#all_admins"
  get "/all_transactions" => "admins#all_transactions"
  get "/view_transaction/:id" => "admins#view_transaction", as: "view_transaction"
  post "/users/:id/confirm_user" => "users#confirm_user", as: "confirm_user"
  post "/users/:id/approve_application" => "users#approve_application", as: "approve_application"
  post "/users/:id/deny_application" => "users#deny_application", as: "deny_application"
  post "/users/:id/verify_user" => "dashboard#verify_user", as: "verify_user"

  resources :wallets, only: [ :show ], shallow: true do
    resources :transactions, only: [ :index, :show, :new, :create ]
    resources :investments, only: [ :index, :show ]
  end

  resources :stocks, only: [ :show, :index ]

  get "/user_profile" => "dashboard#user_profile", as: "user_profile"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  scope :pending_users, -> { where("user_status == pending") }

  validates :first_name, presence: true
  validates :last_name, presence: true

  enum :user_status, { buyer_only: 0, buyer_broker: 1, deactivated: 2, pending: 3 }
  enum :user_role, { buyer: 0, admin: 1, broker: 2 }

  has_one :wallet

  after_create :create_wallet

  private
  def create_wallet
    Wallet.create!(
      user: self,
      balance: 0,
    )
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if is_user_admin
    @users = User.all
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def show
    if is_user_admin
      @user = User.find(params[:id])
      @wallet = @user.wallet
      @transactions = @wallet.transactions.order(:id)
      @investments = @wallet.investments.order(:id)
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def all_pending_users
    if is_user_admin
      @users = User.pending_users
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def confirm_user
    if is_user_admin
      @user = User.find(params[:id])

      if @user.confirm
        flash[:notice] = "User email confirmed successfully"
        redirect_to user_path(@user)
        nil
      else
        render :show
      end
    end
  end

  def approve_application
    @user = User.find(params[:id])

    if @user.user_status == "pending"
        @user.user_status = "buyer_broker"

      if @user.save
        flash[:notice] = "User is now a broker!"
        puts "user status after @user.update: #{@user.user_status}"
        BrokerMailer.with(user: @user).broker_approved.deliver_now
        redirect_to all_pending_users_path
        nil
      else
        flash[:alert] = "Error occurred"
        render :all_pending_users
      end
    else
      flash[:notice] = "Error occurred"
    end
  end

  def deny_application
    @user = User.find(params[:id])

    if @user.user_status == "pending"
        @user.user_status = "buyer_only"

      if @user.save
        flash[:notice] = "User's application was denied"
        puts "user status after @user.update: #{@user.user_status}"
        BrokerMailer.with(user: @user).broker_denied.deliver_now
        redirect_to all_pending_users_path
        nil
      else
        flash[:alert] = "Error occurred"
        render :all_pending_users
      end
    else
      flash[:notice] = "Error occurred"
    end
  end

  def new
    if is_user_admin
      @user = User.new
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def create
    if is_user_admin
      @user = User.new(user_params)

      if params[:commit] == "Submit and Confirm immediately"
        @user.skip_confirmation!
        if @user.save
          flash[:notice] = "User created successfully and email is simultaneously confirmed"
          redirect_to user_path(@user) and return
        end
      else
        if @user.save
          flash[:notice] = "User created successfully"
          redirect_to user_path(@user) and return
        end
      end
      redirect_to new_admin_user_path, alert: "Unable to create user"
    end
  end

  def edit
    if is_user_admin
      @user = User.find(params[:id])
      render :edit
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def update
    if is_user_admin
      @user = User.find(params[:id])

      if @user.update(user_params)
        flash[:notice] = "User credentials changed successfully"
        redirect_to user_path(@user)
        nil
      else
        flash[:alert] = "User credentials couldn't be saved"
        redirect_to edit_user_path(@user)
        nil
      end
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  def destroy
    if is_user_admin
      @user = User.find(params[:id])

      if @user.destroy
        redirect_to all_users_path
        nil
      else
        p @user.errors.messages
      end
    else
      redirect_to dashboard_path, alert: "User is unauthorized"
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_role, :user_status, :email, :password,)
  end

  def is_user_admin
    current_user.user_role == "admin"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_investment_table.html.erb
<% if investments.empty? %>
  <p>No investments to display</p>
<% else %>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">Stock Symbol</th>
        <th class="<%=admin_thead_border%>">Shares</th>
        <th class="<%=admin_thead_border%>">Buy Price</th>
      </tr>
    </thead>
    <tbody>
    <% investments.each do |inv| %>
      <tr>
        <td><%= inv.id %> </td>
        <td><%= Stock.find(inv.stock_id).symbol %> </td>
        <td><%= inv.total_share_amount %> </td>
        <td><%= inv.buying_price.format %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_transaction_table.html.erb
<% if transactions.empty? %>
  <p>No transactions to display</p>
<% else %>
  <table class="<%=admin_table%>">
    <thead>
      <tr>
        <th class="<%=admin_thead_border%>">ID</th>
        <th class="<%=admin_thead_border%>">Stock Symbol</th>
        <th class="<%=admin_thead_border%>">Shares</th>
        <th class="<%=admin_thead_border%>">Amount</th>
      </tr>
    </thead>
    <tbody>
    <% transactions.each do |tx| %>
      <tr>
        <td><%= tx.id %> </td>
        <td><%= tx.stock_symbol %> </td>
        <td><%= tx.share_amount %> </td>
        <td><%= tx.price.format %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/edit.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> mt-[1rem]">
  <%= form_with scope: :user, url: user_path, method: :patch, local: true do |f| %>
  <%= render '/shared/users/form', f: f%>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> mt-[1rem]">
  <%= form_with scope: :user, url: admin_users_path, local: true do |f| %>
  <%= render '/shared/users/form', f: f%>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'admins/admin_top_bar'%>
<div class="<%=admin_flex_col_container%> mt-[1rem]">
  <h1 class="<%=admin_main_header%> px-[1rem]">User #<%=@user.id%> : <%= @user.first_name %> <%= @user.last_name %></h1>
  <div class="<%=admin_flex_col_container%> px-[1rem]">
    <div class="<%=admin_divider%>"></div>
    <p>First Name : <%= @user.first_name %></p>
    <p>Last Name : <%= @user.last_name %></p>
    <p>Role : <%= @user.user_role %> </p>
    <p>Status : <%= @user.user_status %> </p>
    <p>Wallet Balance : <%= @wallet.balance.format %> </p>
    <% if @user.confirmed_at == nil   %>
    <p> Account not confirmed </p>
    <% else %>
    <p>Account Confirmed : <%= @user.confirmed_at %></p>
    <% end %>

    <div class="<%= admin_flex_row_container %>">
    <% if @user.confirmed_at == nil %>
    <%= button_to image_tag('icons/ConfirmUser.png', height:21, width:21 ) +"Confirm Email", confirm_user_path, method: :post, :class=> admin_dashboard_button %>
    <% end %>
    <%= button_to image_tag('icons/EditUser.png', height:21, width:21 ) +'Edit User', edit_user_path(@user), method: :get, :class=> admin_dashboard_button %>
    <%= button_to image_tag('icons/DeleteUser.png', height:21, width:21 ) +"Delete User", user_path(@user), data:{ turbo_method: :delete, turbo_confirm: 'Are you sure?' }, method: :delete, :class=> admin_dashboard_button %>
    </div>

    <p class="<%=admin_mini_header%>">Transactions : <%= @transactions.count %> </p>
    <%= render 'users/transaction_table', transactions: @transactions %>
    <p class="<%=admin_mini_header%>">Investments : <%= @investments.count %> </p>
    <%= render 'users/investment_table', investments: @investments %>
  </div>
</div>