config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  root "welcome#index"
  get "dashboard" => "dashboard#index", as: :dashboard

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :admins, shallow: true do
    resources :users
  end

  # Extra admin paths
  get "/all_users" => "admins#all_users"
  get "/all_pending_users" => "admins#all_pending_users"
  get "/all_admins" => "admins#all_admins"
  get "/all_transactions" => "admins#all_transactions"
  get "/view_transaction/:id" => "admins#view_transaction", as: "view_transaction"
  post "/users/:id/confirm_user" => "users#confirm_user", as: "confirm_user"
  post "/users/:id/approve_application" => "users#approve_application", as: "approve_application"
  post "/users/:id/deny_application" => "users#deny_application", as: "deny_application"
  post "/users/:id/verify_user" => "dashboard#verify_user", as: "verify_user"

  resources :wallets, only: [ :show ], shallow: true do
    resources :transactions, only: [ :index, :show, :new, :create ]
    resources :investments, only: [ :index, :show ]
  end

  resources :stocks, only: [ :show, :index ]

  get "/user_profile" => "dashboard#user_profile", as: "user_profile"
end

app/views/shared/_flash.html.erb
<div class="absolute w-full flex items-center justify-center text-center top-0.5 z-10">
  <% if flash.any? %>
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
          <div class="py-2 px-4 font-bold text-white bg-[green]">
          <%= msg %>
          </div>
        <% else %>
          <div class="py-2 px-4 font-bold text-white bg-[red]">
          <%= msg %>
          </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
    <div class="grid1 h-full bg-[#8B7DC3] font-bold text-white flex flex-col items-center justify-between">
      
      <div class="fixed h-screen flex flex-col items-center justify-between pt-5 pb-5 ">
        <div class="flex items-center justify-center gap-2 p-3 text-[2rem]">
          <img src="<%= image_path('icons/JuanStocksIcon.png')%>" class="max-w-[40px] max-h-[40px]">
          <div >JuanStocks</div>
        </div>

        <div class="flex flex-col items-center justify-center w-full">
          <div class="flex flex-col items-start justify-start">
            <div class="<%=navbar_icons%>"><img src="<%= image_path('icons/Dashboard.png')%>" class="max-w-[40px] max-h-[40px] text-[2rem]"><div class="text-[1.6rem]"><%= link_to "Dashboard", dashboard_path %></div></div>
            <div class="<%=navbar_icons%>"><img src="<%= image_path('icons/Stock Market.png')%>" class="max-w-[40px] max-h-[40px] text-[2rem]"><div class="text-[1.6rem]"><%= link_to "Stock Market", stocks_path %></div></div>
            <div class="<%=navbar_icons%>"><img src="<%= image_path('icons/Wallet.png')%>" class="max-w-[40px] max-h-[40px] text-[2rem]"><div class="text-[1.6rem]"><%= link_to "Wallet", wallet_path(current_user.id) %></div></div>
            <div class="<%=navbar_icons%>"><img src="<%= image_path('icons/Portfolio.png')%>" class="max-w-[40px] max-h-[40px] text-[2rem]"><div class="text-[1.6rem]"><%= link_to "Portfolio", wallet_investments_path(current_user.id) %></div></div>
            <div class="<%=navbar_icons%>"><img src="<%= image_path('icons/User Profile.png')%>" class="max-w-[40px] max-h-[40px] text-[2rem]"><div class="text-[1.6rem]"><%= link_to "User Profile", user_profile_path %></div></div>
          </div>
        </div>

          <div class="flex items-center justify-center text-[1.28rem] w-[50%]">
            <img src="<%= image_path('icons/Sign Out.png')%>" class="max-w-[30px] max-h-[30px]">
            <div><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "hover:underline hover:cursor-pointer" %></div>
          </div>
      </div>
    </div>

app/views/shared/_stock_card.html.erb
<div class="grid grid-cols-2 items-center justify-center gap-2 p-5">

  <div class="grid1 h-auto overflow-visible whitespace-nowrap">
    <div class="flex items-center justify-start w-full gap-3">
        <div class="rounded-[50%]"><%= image_tag stock.display_symbol, class: "rounded-[50%] max-w-[70px]" %></div>
        <div class="font-bold border-[1px] rounded-[4px] text-[1.4rem] pl-2 pr-2 pt-0 pb-0"><%= stock.symbol %></div>
        <div class="font-bold text-[2rem] whitespace-nowrap"><%= stock.description %></div>
    </div>

      <div class="flex items-center justify-start gap-4 w-full pt-2 pb-2 h-full">

        <div class="Labels gap-2 p-3 h-full font-[500] text-[1.2rem]">
          <div>High Price of the Day</div>
          <div>Low Price of the Day</div>
          <div>Open Price of the Day</div>
          <div>Previous Closing Price</div>
        </div>

        <div class="Data gap-2 h-full text-[1.2rem] font-[500]">
          <div>$ <%= round_off(stock.high_price_of_the_day_cents) %></div>
          <div>$ <%= round_off(stock.low_price_of_the_day_cents) %></div>
          <div>$ <%= round_off(stock.open_price_of_the_day_cents) %></div>
          <div>$ <%= round_off(stock.previous_close_price_cents) %></div>
        </div>
      </div>

  </div>
    
  <div class="grid2 flex items-end h-full pb-0 mb-0">
      <div class="flex items-end justify-center gap-2 w-full h-full">
        <div class="text-[2.5rem] font-bold">$<%= round_off(stock.high_price_of_the_day_cents) %></div>
        <% if stock.percent_change.negative? %>
        <div class="bg-[hsl(0,54%,52%)] text-white flex p-2 rounded-[5px] items-center justify-center gap-1 font-bold"><img src="<%= image_path('icons/Polygon_1.png')%>"><%= stock.percent_change.round(2) %></div>
        <% else %>
        <div class="bg-[hsl(120,40%,50%)] text-white flex p-2 rounded-[5px] items-center justify-center gap-1 font-bold"><img src="<%= image_path('icons/Polygon_1.png')%>" class="text-white max-h-3 max-w-3"><%= stock.percent_change.round(2) %></div>
        <% end %>
    </div>
  </div>

</div>

app/views/shared/_stocks_table.html.erb
 <tbody class="pt-2 m-2">
  <tr class="m-1 font-bold hover:bg-[#f1eff7]">
    <td class="m-2 p-2 w-[5%]"><%= image_tag stock.display_symbol, :class => "rounded-[50%]"  %> </td>
    <td class="m-2 p-2 "><%= stock.symbol %> </td>
    <td class="m-2 p-2 "><%= stock.description %> </td>
    <td class="m-2 p-2 "><%= stock.current_price.format %> </td>
    <td class="m-2 p-2 "><%= stock.change %> </td>
    <td class="m-2 p-2 "><%= stock.percent_change %> </td>
    <td class="m-2 p-2 "><%= stock.high_price_of_the_day.format %> </td>
    <td class="m-2 p-2 "><%= stock.low_price_of_the_day.format %> </td>
    <td class="m-2 p-2 "><%= stock.current_price_currency %> </td>
    <td class="m-2 p-2"><%= link_to "Stock Info", stock_path(stock.id), class: "text-[#8B7DC3] hover:underline"  %> </td>
  </tr>
</tbody>